"""
This type stub file was generated by pyright.
"""

from . import *

class GLTFValidatorException(Exception):
    ...


class InvalidAcccessorComponentTypeException(GLTFValidatorException):
    ...


class InvalidBufferViewIndex(GLTFValidatorException):
    ...


class InvalidAccessorSparseIndicesComponentTypeException(GLTFValidatorException):
    ...


class InvalidArrayLengthException(GLTFValidatorException):
    ...


class MismatchedArrayLengthException(GLTFValidatorException):
    ...


class InvalidMeshPrimitiveMode(GLTFValidatorException):
    ...


class InvalidValueError(GLTFValidatorException):
    ...


class InvalidBufferViewTarget(GLTFValidatorException):
    ...


class MissingRequiredField(GLTFValidatorException):
    ...


def validate_accessors(gltf: GLTF2): # -> None:
    ...

def validate_accessors_sparse(gltf: GLTF2): # -> None:
    ...

def validate_animation_channel(gltf: GLTF2): # -> None:
    ...

def validate_meshes(gltf: GLTF2): # -> None:
    ...

def validate_bufferViews(gltf: GLTF2): # -> None:
    ...

def validate(gltf: GLTF2, warning=...): # -> list[Any]:
    """
    Validate a GLTF2 object. Will raises exceptions where validation fails.

    Args:
          gltf (GLTF2): A gltf2 object
          warning (Bool): If false, all errors throw exceptions, else

    Returns:
         errors List(Exception): A list of errors if warning is True, or an empty list validated correctly
    """
    ...

def summary(gltf: GLTF2): # -> None:
    ...

